- name: install Python bindings
  yum: name=libselinux-python state=present
  when: ansible_os_family  == "RedHat"

- name: disable SELinux
  selinux: state=disabled
  when: ansible_os_family  == "RedHat"
